---


- name: add users
  hosts: all
  become: yes
  

  tasks:

  - name: add user ansible
    user:
      name: ansible
      state: present
      create_home: no
            
  - name: Create html file
    copy:
      dest: /etc/sudoers.d/ansible
      content: "ansible ALL=(ALL) NOPASSWD:ALL"
